spring.application.name=campusconnect-backend

# Legacy & modern Spring Data MongoDB property keys
spring.data.mongodb.uri=mongodb://localhost:27017/campusconnectdb
spring.data.mongodb.database=campusconnectdb
spring.mongodb.database=campusconnectdb

server.port=8080